
const championFlexRoles: Record<string, string[]> = {
    aatrox: ["top"],
    akali: ["mid", "top"],
    akshan: ["mid", "top"],
    alistar: ["support"],
    ambessa: ["top"],
    amumu: ["jungle", "support"],
    anivia: ["mid"],
    annie: ["mid", "support"],
    aphelios: ["bottom"],
    ashe: ["bottom", "support"],
    aurelionsol: ["mid"],
    aurora: ["mid"],
    azir: ["mid"],
    bard: ["support"],
    belveth: ["jungle"],
    blitzcrank: ["support"],
    brand: ["support", "mid"],
    braum: ["support"],
    briar: ["jungle"],
    caitlyn: ["bottom"],
    camille: ["top", "jungle"],
    cassiopeia: ["mid"],
    chogath: ["top", "jungle"],
    corki: ["mid"],
    darius: ["top"],
    diana: ["jungle", "mid"],
    draven: ["bottom"],
    drmundo: ["top", "jungle"],
    ekko: ["jungle", "mid"],
    elise: ["jungle"],
    evelynn: ["jungle"],
    ezreal: ["bottom"],
    fiddlesticks: ["jungle"],
    fiora: ["top"],
    fizz: ["mid", "jungle"],
    galio: ["mid", "support", "top"],
    gangplank: ["top"],
    garen: ["top"],
    gnar: ["top"],
    gragas: ["jungle", "top", "support"],
    graves: ["jungle"],
    guangyuan: ["top"],
    hecarim: ["jungle"],
    heimerdinger: ["mid", "top"],
    hwei: ["mid", "support"],
    illaoi: ["top"],
    irelia: ["top", "mid"],
    ivern: ["jungle", "support"],
    janna: ["support"],
    jarvaniv: ["jungle"],
    jax: ["top", "jungle"],
    jayce: ["top", "mid"],
    jhin: ["bottom"],
    jinx: ["bottom"],
    kaisa: ["bottom"],
    kalista: ["bottom"],
    karma: ["support", "mid"],
    karthus: ["jungle"],
    kassadin: ["mid"],
    katarina: ["mid"],
    kayle: ["top"],
    kayn: ["jungle"],
    kennen: ["top", "mid"],
    khazix: ["jungle"],
    kindred: ["jungle"],
    kled: ["top"],
    kogmaw: ["bottom"],
    leblanc: ["mid"],
    leesin: ["jungle"],
    leona: ["support"],
    lillia: ["jungle", "mid"],
    lissandra: ["mid"],
    lucian: ["bottom", "mid"],
    lulu: ["support"],
    lux: ["support", "mid"],
    malphite: ["top", "support", "mid"],
    malzahar: ["mid"],
    maokai: ["support", "top", "jungle"],
    masteryi: ["jungle"],
    mellow: ["mid"],
    milio: ["support"],
    missfortune: ["bottom"],
    mordekaiser: ["top"],
    morgana: ["support", "mid"],
    naafiri: ["mid"],
    nami: ["support"],
    nasus: ["top"],
    nautilus: ["support"],
    neeko: ["mid", "support"],
    nidalee: ["jungle"],
    nilah: ["bottom"],
    nocturne: ["jungle"],
    nunu: ["jungle"],
    olaf: ["jungle", "top"],
    orianna: ["mid"],
    ornn: ["top"],
    pantheon: ["support", "mid", "top"],
    poppy: ["jungle", "top", "support"],
    pyke: ["support", "mid"],
    qiyana: ["mid"],
    quinn: ["top", "mid"],
    rakan: ["support"],
    rammus: ["jungle"],
    reksai: ["jungle"],
    rell: ["support"],
    renata: ["support"],
    renekton: ["top"],
    rengar: ["jungle"],
    riven: ["top"],
    rumble: ["top", "mid"],
    ryze: ["mid"],
    samira: ["bottom"],
    sejuani: ["jungle"],
    senna: ["support", "bottom"],
    seraphine: ["support", "mid"],
    sett: ["top", "support", "jungle"],
    shaco: ["jungle", "support"],
    shen: ["top", "support"],
    shyvana: ["jungle"],
    singed: ["top"],
    sion: ["top", "support"],
    sivir: ["bottom"],
    skarl: ["jungle"],
    smolder: ["bottom"],
    sona: ["support"],
    soraka: ["support"],
    swain: ["support", "mid"],
    sylas: ["mid", "jungle"],
    syndra: ["mid"],
    tahmkench: ["top", "support"],
    taliyah: ["jungle", "mid"],
    talon: ["mid", "jungle"],
    taric: ["support", "top"],
    teemo: ["top"],
    thresh: ["support"],
    tristana: ["bottom"],
    trundle: ["jungle", "top"],
    tryndamere: ["top"],
    twinfang: ["mid"],
    twitch: ["bottom"],
    udyr: ["jungle", "top"],
    urgat: ["top"],
    varus: ["bottom"],
    vayne: ["bottom", "top"],
    veigar: ["mid"],
    velkoz: ["mid", "support"],
    vex: ["mid"],
    vi: ["jungle"],
    viego: ["jungle"],
    viktor: ["mid"],
    vladimir: ["mid", "top"],
    volibear: ["top", "jungle"],
    warwick: ["jungle", "top"],
    monkeyking: ["top", "jungle"],
    xayah: ["bottom"],
    xerath: ["mid", "support"],
    xinzhao: ["jungle"],
    yasuo: ["mid", "top"],
    yone: ["mid", "top"],
    yorick: ["top"],
    yuumi: ["support"],
    zac: ["jungle"],
    zed: ["mid"],
    zeri: ["bottom"],
    ziggs: ["mid", "support"],
    zilean: ["support"],
    zoe: ["mid"],
    zyra: ["support", "mid"],
};

export default championFlexRoles;